volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true
services:
  fastapi:
    build:
      context: sample_service
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    volumes:
      - ./sample_service:/app
  postgres:
        build:
            context: ./relational-data
            dockerfile: ./Dockerfile.dev
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_MULTIPLE_DATABASES: customersdb,deliveriesdb,pharmacydb,usersdb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin123
        ports:
            - 15432:5432
  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
  customers:
    build:
        context: ./customers
        dockerfile: ./Dockerfile.dev
    ports:
        - "8001:8000"
    volumes:
        - ./customers:/app
    environment:
      DATABASE_URL: postgresql://admin:password@postgres/customersdb
      WAIT_HOSTS: postgres:5432

  deliveries:
    build:
        context: ./deliveries
        dockerfile: ./Dockerfile.dev
    ports:
        - "8002:8000"
    volumes:
        - ./deliveries:/app
    environment:
      DATABASE_URL: postgresql://admin:password@postgres/deliveriesdb
      WAIT_HOSTS: postgres:5432

  pharmacy:
    build:
        context: ./pharmacy
        dockerfile: ./Dockerfile.dev
    ports:
        - "8003:8000"
    volumes:
        - ./pharmacy:/app
    environment:
      DATABASE_URL: postgresql://admin:password@postgres/pharmacydb
      WAIT_HOSTS: postgres:5432
  users:
    build:
        context: ./users
        dockerfile: ./Dockerfile.dev
    ports:
        - "8004:8000"
    volumes:
        - ./users:/app
    environment:
      DATABASE_URL: postgresql://admin:password@postgres/usersdb
      WAIT_HOSTS: postgres:5432
  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@epsilon.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
